name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (for example, if you're deploying a Node.js app)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        
    # Replace the incorrect action with a valid one
      - name: Trigger another workflow
        uses: actions/github-script@v3
        with:
          script: |
            const context = github.context;
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy.yml',
              ref: 'main'
            });

  # approve:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: ${{ github.event_name == 'push' }}

  #   steps:
  #     - name: Request approval
  #       run: echo "Waiting for approval before deploying."
  #       id: approval

  #     - name: Check for approval (manual approval step)
  #       uses: peter-evans/workflow-dispatch@v1
  #       with:
  #         workflow: 'deploy.yml'  # This is the next workflow that will run for deployment.
  #         ref: refs/heads/main
  
