name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (for example, if you're deploying a Node.js app)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  approval:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}

    steps:
      - name: Notify for manual approval
        run: echo "Manual approval is required before deployment. Please approve in the next workflow."
        
      - name: Trigger Deploy Workflow
        run: |
          echo "Triggering deploy workflow after approval."
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"event_type": "deploy_approval"}' \
            "https://api.github.com/repos/${{ github.repository }}/dispatches"
